services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: biocol-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: biocol_import
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - biocol-network

  # Redis for caching (optional for future use)
  redis:
    image: redis:7-alpine
    container_name: biocol-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - biocol-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: biocol-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/biocol_import?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - biocol-network
    command: npm run dev

  # Frontend (development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: biocol-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - biocol-network
    command: npm run dev -- --host

volumes:
  postgres_data:

networks:
  biocol-network:
    driver: bridge